-- 테이블 레코드 번호 갱신(앞에 번호)
SET @CNT = 0;
UPDATE PRODUCTS SET PRODUCTS.pID = @CNT:=@CNT+1;

SET @CNT = 0;
UPDATE CUSTOMERS SET CUSTOMERS.cID = @CNT:=@CNT+1;

SET @CNT = 0;
UPDATE ORDERS SET ORDERS.oID = @CNT:=@CNT+1;

SET SQL_SAFE_UPDATES = 0;

-- 테이블 스키마 확인
DESC CUSTOMERS;
DESC ORDERS;
DESC PRODUCTS;

-- 해당 테이블 모든 튜플 조회
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;

-- INSERT문 : CUSTOMERS
INSERT INTO CUSTOMERS(CUSTOMERS.cNAME, CUSTOMERS.cPW, CUSTOMERS.cNICKNAME, CUSTOMERS.cEMAIL, CUSTOMERS.cMODE, CUSTOMERS.cBALANCE) VALUES ('정민영', '1111', 'manduMY', 'manduMY@naver.com', '0', '10000');
INSERT INTO CUSTOMERS(CUSTOMERS.cNAME, CUSTOMERS.cPW, CUSTOMERS.cNICKNAME, CUSTOMERS.cEMAIL, CUSTOMERS.cMODE, CUSTOMERS.cBALANCE) VALUES ('권동희', '2222', 'Donghee', 'Donghee@naver.com', '0', '10000');
INSERT INTO CUSTOMERS(CUSTOMERS.cNAME, CUSTOMERS.cPW, CUSTOMERS.cNICKNAME, CUSTOMERS.cEMAIL, CUSTOMERS.cMODE, CUSTOMERS.cBALANCE) VALUES ('김영현', '3333', 'ZeroHyun', 'Zerohyun@naver.com', '0', '10000');
INSERT INTO CUSTOMERS(CUSTOMERS.cNAME, CUSTOMERS.cPW, CUSTOMERS.cNICKNAME, CUSTOMERS.cEMAIL, CUSTOMERS.cMODE, CUSTOMERS.cBALANCE) VALUES ('이헌기', '4444', 'gjsrl1', 'gjsrl1@naver.com', '0', '10000');
INSERT INTO CUSTOMERS(CUSTOMERS.cNAME, CUSTOMERS.cPW, CUSTOMERS.cNICKNAME, CUSTOMERS.cEMAIL, CUSTOMERS.cMODE, CUSTOMERS.cBALANCE) VALUES ('user', '1111', 'ㅇㅇ', '1', '10000');

-- INSERT문 : PRODUCTS
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('신라면', 2000, '라면류', '농심');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('짜파게티', 2500, '라면류', '농심');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('간짬뽕', 1500, '라면류', '삼양');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('진라면', 1000, '라면류', '오뚜기');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('참깨라면', 1300, '라면류', '오뚜기');

INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('미에로화이바', 700, '음료류', '미에로');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('밀키스', 800, '음료류', '롯데');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('덴마크민트초코우유', 1500, '음료류', '덴마크밀크');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('블루레몬에이드', 900, '음료류', 'CU');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('트로피카나스파클링', 1000, '음료류', '트로피카나');

INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('미쯔블랙', 1400, '과자류', '오리온제과');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('프링글스', 3000, '과자류', 'kellogg_Asia');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('화이트하임', 1400, '과자류', '크라운');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('카라멜땅콩', 1500, '과자류', '크라운');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('칸쵸', 1000, '과자류', '롯데제과');

INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('휠터치', 750, '간식류', '대림수산');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('굿다리', 1400, '간식류', '정화식품');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('땅콩_버터구이_오징어', 1500, '간식류', '정화식품');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('숯불구이맛_핫바', 700, '간식류', '대림수산');
INSERT INTO PRODUCTS(PRODUCTS.pNAME, PRODUCTS.pPRICE, PRODUCTS.pTYPE, PRODUCTS.pMANUF) VALUES('구운_순살_쥐포', 1000, '간식류', '서울지앤비');

INSERT INTO ORDERS(ORDERS.CUSTOMERS_cID, ORDERS.PRODUCTS_pID, ORDERS.oCNT, ORDERS.oDATE) VALUES(1, 5, 1, '2019-12-30 17:45:30');
INSERT INTO ORDERS(ORDERS.CUSTOMERS_cID, ORDERS.PRODUCTS_pID, ORDERS.oCNT, ORDERS.oDATE) VALUES(2, 3, 2, '2020-01-01 18:00:00');
INSERT INTO ORDERS(ORDERS.CUSTOMERS_cID, ORDERS.PRODUCTS_pID, ORDERS.oCNT, ORDERS.oDATE) VALUES(3, 10, 1, '2019-12-30 09:30:45');
INSERT INTO ORDERS(ORDERS.CUSTOMERS_cID, ORDERS.PRODUCTS_pID, ORDERS.oCNT, ORDERS.oDATE) VALUES(4, 15, 3, '2019-12-31 11:45:18');
INSERT INTO ORDERS(ORDERS.CUSTOMERS_cID, ORDERS.PRODUCTS_pID, ORDERS.oCNT, ORDERS.oDATE) VALUES(5, 13, 5, '2019-12-31 21:55:39');-- 5번고객이 13번째 품목을 5개 구매


-- 테이블의 모든 레코드를 삭제한다.
DELETE FROM CUSTOMERS;
DELETE FROM PRODUCTS;
DELETE FROM ORDERS;

-- 컬럼기준 정렬(오름/내림 차순)
SELECT * FROM ORDERS ORDER BY oDATE ASC;
SELECT * FROM ORDERS ORDER BY oDATE DESC;

-- 다중 정렬(pair 정렬)
	-- 주문 횟수(oCNT)가 같을 경우 oDATE순으로 오름차순 정렬. 
	SELECT * FROM ORDERS ORDER BY oCNT, oDATE ASC;
    